# Generated by Django 2.2.13 on 2020-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201214_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
