# Generated by Django 2.2.13 on 2020-12-14 10:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201214_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
