# Generated by Django 3.0.6 on 2020-12-08 13:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('NIP', models.DecimalField(blank=True, decimal_places=0, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('email', models.EmailField(blank=True, max_length=320, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
